# package directories missing from upstream tmpfiles declarations
d /var/cache/ibus 0755 root root - -
d /var/cache/ibus/bus 0755 root root - -
d /var/cache/libX11 0755 root root - -
d /var/cache/libX11/compose 0755 root root - -
d /var/cache/libdnf5 0755 root root - -
d /var/cache/swcatalog 0755 root root - -
d /var/cache/swcatalog/cache 0755 root root - -
d /var/cache/swcatalog/gv 0755 root root - -
d /var/cache/swcatalog/icons 0755 root root - -
d /var/cache/swcatalog/xml 0755 root root - -
d /var/lib/AccountsService 0775 root root - -
d /var/lib/AccountsService/icons 0775 root root - -
d /var/lib/AccountsService/users 0700 root root - -
d /var/lib/color 0755 root root - -
d /var/lib/color/icc 0755 root root - -
d /var/lib/geoclue 0755 geoclue geoclue - -
d /var/lib/tuned 0755 root root - -
d /var/log/tuned 0755 root root - -
